esphome:
  name: heater-simulator

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   password: ""

# ota:
#   - platform: esphome
#     password: ""

# wifi:
#   ssid: ZagrodySzopenChoj
#   password: j6dbv7mo8996

# captive_portal:

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [diesel_heater]

diesel_heater:
  data_pin: 5
  debug_pin: 4
